INSERT INTO ITEM(NAME, POINTS) VALUES ("Water", 4);
INSERT INTO ITEM(NAME, POINTS) VALUES ("Food", 3);
INSERT INTO ITEM(NAME, POINTS) VALUES ("Medication", 2);
INSERT INTO ITEM(NAME, POINTS) VALUES ("Ammunition", 1);